name: CICD

#manual click (deliver)  workflow when user needs
on:
  workflow_dispatch:
    inputs:
      environment:
        description: This is the environment value where work flow runs
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - prod
          - staging

jobs:

#Every jobs need seperate runner is called paralliesm
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "Code clone from github"

  build:
    needs: code
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Container
        run: echo "Build docker file and run container"

  test:
    needs: [build,code]
    runs-on: ubuntu-latest
    steps:
      - name: Test the container
        run: echo "Testing the container"


  deploy:
    if: inputs.environment == 'dev'
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploying app via compose
        run: echo "Deploy app thru Docker Compose"
