#package- issues ya vulnerablities (scan)
# pip-audit
name: Dependency Scan

on:
    workflow_call:

jobs:
    dependency-scan:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              run: actions/checkout@v4

            - name: Set up Python 3.12
              uses: actions/setup-python@v5
              with:
                python-version: "3.12"

            - name: Install Pip audit
              run: pip install pip-audit

            - name: Audit Dependencies
              run: pip-audit -r requirements.txt


