name: DevSecOps End to End Pipeline

on:
    push:
        branches: [main]


jobs:
    # CI [Continious Integration for security scaning]
    Code-Quality:
        uses: ./.github/workflows/code-scan.yml

    Secrets-scan:
        uses: ./.github/workflows/secrets-scan.yml
        secrets: inherit

    dependency-scan:
        uses: ./.github/workflows/dependency-scan.yml

    docker-scan:
        uses: ./.github/workflows/docker-lint.yml

  #build once the security scan are complete
    build:
        needs: [Code-Quality,Secrets-scan,dependency-scan,docker-scan]
        uses: ./.github/workflows/docker-build-push.yml
        secrets: inherit
    
    trivy:
        needs: [build]
        uses: ./.github/workflows/image-scan.yml
        secrets: inherit

    deploy:
        needs: [trivy]
        uses: ./.github/workflows/deploy-to-server.yml
        secrets: inherit

