#name of work flow
name: hello

# When workflow is start
on:
  push:
    branches: [main]
    paths:
      - '**.yml'
      - '**.yaml'
      - '**.html'

#job inside in workflow
jobs:

#jobs name
  greet:

  #This is github runner
    runs-on: ubuntu-latest

#step of jobs
    steps:
      - name: Say hello Dosto
        run: echo "Hello Dosto Kaise ho App"

      - name: Say the username
        run: echo "Hello $USER"
    
  details:
    runs-on: ubuntu-latest

    steps:
      - name: versions of docker & Python
        run: docker --version && python --version

      
