name: multi job workflow

on:
    workflow_dispatch:
    # push:
    #     branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Building the application
              run: echo "Building the app"
    test:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Running tests
              run: echo "Running tests"
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:  
            - name: Deploying the application
              run: echo "Deploying"
              
            
