name: PR Check

on:
    pull_request:
        branches: [main]
        types: [opened, synchronize, reopened]
    schedule:
        - cron: '0 0 * * *' # Runs every day at midnight


jobs:
    pr-check:
        runs-on: ubuntu-latest
        steps:

            - name: PR check is runnning
              run: echo "PR check running for branch ${{ github.head_ref }}"
    
    run-schedule:
        runs-on: ubuntu-latest
        steps:
            - name: Schedule check is running
              run: echo "Schedule check running at $(date)"          